CREATE TABLE Customer (
    customer_id INTEGER NOT NULL,
    age INTEGER NOT NULL,
    income NUMERIC(12,2),
    risk_profile VARCHAR(20),
    customer_segment VARCHAR(50),
    PRIMARY KEY (customer_id)
);

CREATE TABLE Account (
    account_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    account_type VARCHAR(30) NOT NULL,
    balance NUMERIC(12,2),
    opened_date DATE,
    PRIMARY KEY (account_id),
    FOREIGN KEY (customer_id)
        REFERENCES Customer(customer_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE Transactions (
    transaction_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    transaction_date DATE NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    category VARCHAR(50),
    transaction_type VARCHAR(20),
    PRIMARY KEY (transaction_id),
    FOREIGN KEY (account_id)
        REFERENCES Account(account_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE Investment (
    investment_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    asset_type VARCHAR(30) NOT NULL,
    sector VARCHAR(50),
    quantity NUMERIC(12,4) NOT NULL,
    purchase_price NUMERIC(12,2) NOT NULL,
    purchase_date DATE NOT NULL,
    PRIMARY KEY (investment_id),
    FOREIGN KEY (customer_id)
        REFERENCES Customer(customer_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE SavingsGoal (
    goal_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    goal_name VARCHAR(100) NOT NULL,
    target_amount NUMERIC(12,2) NOT NULL,
    current_amount NUMERIC(12,2) NOT NULL,
    target_date DATE,
    PRIMARY KEY (goal_id),
    FOREIGN KEY (customer_id)
        REFERENCES Customer(customer_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE MarketData (
    market_data_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY,
    ticker VARCHAR(10) NOT NULL,
    market_date DATE NOT NULL,
    open_price NUMERIC(12,2),
    high_price NUMERIC(12,2),
    low_price NUMERIC(12,2),
    close_price NUMERIC(12,2),
    volume BIGINT,
    PRIMARY KEY (market_data_id),
    CONSTRAINT unique_market_data
        UNIQUE (ticker, market_date)
);